# --- Defaults ---

# --- pymarl options ---
runner: "episode" # Runs 1 env for an episode
mac: "basic_mac" # Basic controller
env: "sc2" # Environment name
env_args: {} # Arguments for the environment
batch_size_run: 1 # Number of environments to run in parallel
test_nepisode: 20 # Number of episodes to test for
test_interval: 2000 # Test after {} timesteps have passed
test_greedy: True # Use greedy evaluation (if False, will set epsilon floor to 0
log_interval: 2000 # Log summary of stats after every {} timesteps
runner_log_interval: 2000 # Log runner stats (not test stats) every {} timesteps
learner_log_interval: 2000 # Log training stats every {} timesteps
t_max: 10000 # Stop running after this many timesteps
use_cuda: True # Use gpu by default unless it isn't available
buffer_cpu_only: True # If true we won't keep all of the replay buffer in vram

# --- Logging options ---
use_tensorboard: False # Log results to tensorboard
save_model: False # Save the models to disk
save_model_interval: 50000 # Save models after this many timesteps
checkpoint_path: "Trained models/MARL/mpe_tag/qmix_seed922421504_mpe%3ASimpleTag-v0_2022-11-29 15%3A56%3A13.207649" # Load a checkpoint from this path
evaluate: True # Evaluate model for test_nepisode episodes and quit (no training)
load_step: 0 # Load model trained on this many timesteps (0 if choose max possible)
save_replay: False # Saving the replay of the model loaded from checkpoint_path
local_results_path: "results" # Path for local results

# --- RL hyperparameters ---
gamma: 0.99
batch_size: 32 # Number of episodes to train on
buffer_size: 32 # Size of the replay buffer
lr: 0.0005 # Learning rate for agents
optim_alpha: 0.99 # RMSProp alpha
optim_eps: 0.00001 # RMSProp epsilon
grad_norm_clip: 10 # Reduce magnitude of gradients above this L2 norm
add_value_last_step: True

# --- Agent parameters ---
agent: "rnn" # Default rnn agent
hidden_dim: 128 # Size of hidden state for default rnn agent
obs_agent_id: True # Include the agent's one_hot id in the observation
obs_last_action: True # Include the agent's last action (one_hot) in the observation

# --- Experiment running params ---
repeat_id: 1
label: "default_label"
hypergroup: null

################################################################################
# --- Tracker Parameters
tracker_buffer_size: 100
tracker_batch_size: 100
tracker_train: False
tracker_window: [-1] #The window size. It should be a list starting with -1, e.g., [-1,10]. For the "no window" case, set it to [-1].
thresholds: [-3]
tracker_load_adr: "Trained Models/Trackers/MPE_Tag/ep_20000"
##################################################################################
# --- Attack Parameters
attack_active: True
attack_type: "DAA" # The options are "OA", "DAA"
attack_start_t: 0  # For a random starting time, set it to -1
attack_max_start: 10 # 25 for SMAC, 10 for LBF&MPE
# --- DAA
adv_exploration_proba_decay: 0.005
adv_batch_size: 32
adv_buffer_size: 1000
adv_max_episode_length: 150  #120 for 2s3z , 150 for 10m_vs_11m, MMM
adv_test_mode: True
adv_load_adr: "Trained Models/DAA/[0.0625, 0.0625, 0.0625, 0.0625]"
lambda_DAA: [0.0625, 0.0625, 0.0625, 0.0625]